---
output:
  md_document:
    variant: markdown_github
---

# worklogAnalyzer

Analyze your worklog (timesheet) history.


## What is a worklogs (timesheet)?

The terms _worklog_ and _timesheet_ appear to be used interchangeably in common usage;
this project uses the term _worklog_ throughout to refer to a record of what work you performed and when you performed it.


## Representing worklogs

## Worklog hierarchy

This project views worklogs as being naturally represented as a hierarchical structure.
For example, you can imagine your worklogs history having multiple projects,
where each project has its own tasks, and those tasks possibly having their own subtasks, and so on.
Of course, if you don't want to represent your worklogs in a hierarchical structure then you can put all of your worklogs in a single level (i.e. a flat structure). 

Representing worklogs in this manner provides several nice abilities.
It can make it easier to understand the structure of your worklogs by showing the relationship between the worklogs in this manner.
You can easily focus on certain subsets of your worklogs history by selecting a subtree of the history.
And you can easily zoom out and zoom in on the level of detail that you want to view your worklogs in by considering any worklogs in a given subtree to all belong to the same level in the hierarchy or vice versa.


## Worklog tags

Sometimes relationships between worklogs cut across the hierarchical structure that you've chosen for your worklogs.
For example, suppose you want to add up the amount of time that you've spent doing code reviews across your various projects.
For this purpose the project has the concept of worklogs being tagged,
meaning that each worklog has 0 or identifiers that can be used to filter on or categorize a tag.


## A basic example

```{r}
library(lubridate)
library(tibble)
library(worklogAnalyzer)

parse_ymdhm <- function(x) {
  parse_date_time(x, "Ymd HM")
}

install_r <- tibble(
  description = "Install latest version of R",
  start       = parse_ymdhm(c("2023-02-14 20:12", "2023-02-15 18:17")),
  end         = parse_ymdhm(c("2023-02-14 20:30", "2023-02-15 18:33")),
  duration    = end - start 
)

dev_r_packages <- tibble(
  description = "Install devtools and testthat",
  start       = parse_ymdhm("2023-02-15 17:55"),
  end         = parse_ymdhm("2023-02-15 18:02"),
  duration    = end - start 
)

create_package <- tibble(
  description = "Run 'create_package' and ''use_testthat'",
  start       = parse_ymdhm("2023-02-15 18:02"),
  end         = parse_ymdhm("2023-02-15 18:09"),
  duration    = end - start 
)

source_worklog <- list(
  "Setup development env" = list(
    "Install newest R"             = install_r,
    "Install development packages" = dev_r_packages
  ),
  "Create R package skeleton" = create_package
)

config <- worklogs_config(
  description_label = "description",
  start_label       = "start",
  end_label         = "end",
  duration          = "duration"
)

wkls <- worklogs(source_worklog, FALSE, config)

wkls
effort_summary(wkls)
```
